<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-19 15:44
=======
# Generated by Django 4.2.1 on 2023-05-19 03:20
>>>>>>> 196b9d31828c44409e78fecd612056085051d8f5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
=======
                ('image', models.ImageField(upload_to='temp')),
>>>>>>> 196b9d31828c44409e78fecd612056085051d8f5
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=150)),
                ('Address', models.CharField(max_length=300)),
                ('Comment', models.TextField()),
            ],
        ),
=======
>>>>>>> 196b9d31828c44409e78fecd612056085051d8f5
    ]
