# Generated by Django 4.2.1 on 2023-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=300)),
                ('MoreDetails', models.TextField()),
                ('occasion', models.CharField(choices=[('Wedding', 'Engagement'), ('Birthday', 'Eid Treats')], max_length=20)),
            ],
        ),
    ]
