# Generated by Django 4.2.1 on 2023-05-19 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_cakes_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cakes',
            new_name='Cake',
        ),
    ]
