# Generated by Django 4.2.1 on 2023-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_cake_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=300)),
                ('MoreDetails', models.TextField()),
                ('occasionn', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('birthday', 'Birthday'), ('eid', 'Eid Treats'), ('other', 'Other'), ('minis', 'Minis')], max_length=20)),
                ('Date', models.DateField()),
                ('number_of_people', models.CharField(choices=[('n', 'Number of People'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', 'More than 8')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=300)),
                ('Comment', models.TextField()),
                ('number_of_people', models.CharField(choices=[('n', 'Number of People'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', 'More than 8')], max_length=1)),
                ('date', models.DateField()),
                ('Email', models.EmailField(max_length=150)),
            ],
        ),
    ]
