# Generated by Django 4.2.1 on 2023-05-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_customform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomForm',
        ),
    ]
