# Generated by Django 4.2.1 on 2023-05-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_test_delete_customform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
