# Generated by Django 4.2 on 2023-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cakes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cake",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cake",
            name="img",
            field=models.ImageField(upload_to="cakes/static/Database/"),
        ),
    ]
